In [1]:
import numpy as np

In [2]:
class _Activation:
    """"""
    def __init__(self):
        """"""
    def rect_lin_act(self, x, w):
        """"""
        mask = x > 0
        mask = mask.astype(np.int)
        x = x*mask
        return np.dot(x,w)
        
    def drect_lin_act(self, x, w):
        """"""
        mask = x > 0
        mask = mask.astype(np.int)
        print(mask)
        print(x)
        return np.multiply(x,mask)

In [3]:
act_func = _Activation()
x = np.array([-1, -2, 3, 5, 6, 7])
w = np.array([11, 12, 13, 14, 15, 16])
act_func.rect_lin_act(x,w)
act_func.drect_lin_act(x,w)

[0 0 1 1 1 1]
[-1 -2  3  5  6  7]


array([0, 0, 3, 5, 6, 7])

In [4]:
class _Node(_Activation):
    """"""
    def __init__(self, inputs, weights, activation):
        """"""
        super().__init__()
        self.inputs = inputs
        self.weights = weights
        self.activation = activation

    def forward(self):
        if activation == 'linear_act':
            return self.lin_act(self.inputs, self.weights)
        elif activation == 'rect_linear_act':
            return self.rect_lin_act(self.inputs, self.weights)
        elif activation == 'tanh':
            return self.tanh(self.inputs, self.weights)
    
    def backwards(self):
        if activation == 'linear_act':
            return self.dlin_act(self.inputs, self.weights)
        elif activation == 'rect_linear_act':
            return self.drect_lin_act(self.inputs, self.weights)
        elif activation == 'tanh':
            return self.dtanh(self.inputs, self.weights)

In [20]:
layer = []
n_nodes = 3
for node in range(n_nodes):
    inputs = np.random.randn(3)
    weights = np.random.randn(3)
    activation = 'rect_linear_act'
    layer.append(_Node(inputs, weights, activation))

In [21]:
new_w = layer[1].weights

In [22]:
new_x = layer[1].inputs

In [23]:
print(layer[1].forward())

-0.04222865432544251


In [24]:
print(layer[1].inputs)
print(layer[1].backwards())

[ 0.09763172 -0.60968008 -1.21279967]
[1 0 0]
[ 0.09763172 -0.60968008 -1.21279967]
[ 0.09763172 -0.         -0.        ]


In [10]:
print(layer[1].forward())

0.0


In [11]:
act2 = _Activation()

In [12]:
act2.rect_lin_act(new_x,new_w)

0.0

In [13]:
new_x

array([-0.06704787, -0.78815491, -0.76112464])

In [14]:
new_w

array([ 0.76006197,  0.43120323, -0.83305128])