In [1]:
import numpy as np

In [42]:
data = np.array([[1,2], [3,4], [5,6]])
labels = np.array([data[i,0]*3 for i in range(data.shape[0])])
data = np.concatenate((data, np.ones((data.shape[0], 1))), axis=1)

In [43]:
data.shape

(3, 3)

In [15]:
# augment data to include biases


In [21]:
weights = np.random.randn(data.shape[1])

In [22]:
weights

array([-0.08358988, -0.38068668, -0.8015887 ])

In [38]:
def linear_regression(data, labels, n_epochs = 300, batch_size=None, loss_tol=0.0001):
    """"""
    nu = 0.01
    n_pts = data.shape[0]
    n_losses = 10
    cum_loss = np.zeros(n_losses)
    if batch_size == None:
        batch_size == n_pts
    else:
        n_batches = np.ceil(n_pts / batch_size)
        batches = [(i*batch_size, (i+1)*batch_size) for i in range(n_batches)]
        batches[n_batches-1][1] = n_pts
    for epoch in range(n_epochs):
        for (start, stop) in batches:
            for i in range(start, stop):
                delta_loss = (np.dot(weights, data[i,:]) - labels[i])*weights
                weights = weights - nu*delta_loss
                if loss_count%n_losses != 0:
                    cum_loss.pop(0)
                    cum_loss.append(delta_loss)
                else:
                    avg_loss = np.sum(cum_loss, axis=0)/n_losses
                    if avg_loss < loss_tol:
                        return weights
    return weights

<ipython-input-38-54b83bc3180c>:5: RuntimeWarning: overflow encountered in multiply
  delta_loss = (np.dot(weights, data[i,:]) - labels[i])*weights


array([-inf, -inf, -inf])

In [37]:
def linear_act(input_data, labels, optimizer='sgd', learning_rate=0.01, optimizer_options = None):
    """"""
    return [np.dot(weights, input_data), weights]

def sq_error_loss(prediction, actual):
    """"""
    return np.sum(np.exp(prediction - actual,2), axis=0)

def optimizer
    

array([-0.76951298, -3.50453122, -7.37927735])

[]